apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vulcan.secretsName }}
data:
  {{- if .Values.vulcan.secrets }}
    {{- range $key, $val := .Values.vulcan.secrets }}
      {{ $key }}: {{ $val | b64enc | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.vulcan.secretsFiles }}
    {{- range $key, $val := .Values.vulcan.secretsFiles }}
      {{ $key }}: {{ $.Files.Get $val | b64enc | quote }}
    {{- end }}
  {{- end }}
  # {{ range .Files.Lines "env/vulcan-secrets.yaml" }}
  #   {{ . }}
  # {{ end }}