{{- if .Values.vulcan.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vulcan.serviceAccountName" . }}
  labels:
    {{- include "vulcan.labels" . | nindent 4 }}
  {{- with .Values.vulcan.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
