apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate
  labels:
    app: {{ template "vulcan.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": {{ .Values.hooks.migrate.hookAnnotation }}
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "-1"
spec:
  template:
    spec:
      restartPolicy: Never
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      initContainers:
      - name: init-postgres
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh"]
        args:
          - -c
          - >-
            PG_READY="pg_isready -h {{ template "vulcan.postgresql.host" . }} -p {{ template "vulcan.postgresql.port" . }}";
            until $PG_READY;
            do
              sleep 2;
            done;
            echo "Database ready to accept connections."  ;
      containers:
      - name: "db-migrate-job"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - echo "Starting Vulcan migration...";
        - bundle
        - exec
        - rails
        - db:vulcan_prepare
        # - db:schema:load db:migrate
        env:
        # {{- if .Values.postgresql.auth.existingSecret }}
        # - name: POSTGRES_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ .Values.postgresql.auth.existingSecret }}
        #       key: {{ default "password" .Values.postgresql.auth.secretKeys.adminPasswordKey }}
        # {{- end }}
        envFrom:
          - secretRef:
              name: {{ template "vulcan.fullname" . }}-env
        # {{- if .Values.existingEnvSecret }}
        #   - secretRef:
        #       name: {{ .Values.existingEnvSecret }}
        # {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      serviceAccountName: {{ include "vulcan.serviceAccountName" . }}
