apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "vulcan.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "vulcan.fullname" . }}-env
data:
  POSTGRES_HOST: {{ include "vulcan.postgresql.host" . | b64enc | quote }}
  POSTGRES_PORT: {{ include "vulcan.postgresql.port" . | b64enc | quote }}
  POSTGRES_USERNAME: {{ default "postgres" .Values.postgresql.auth.username | b64enc | quote }}
  {{- if not .Values.postgresql.auth.existingSecret }}
  POSTGRES_PASSWORD: {{ default "postgres" .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  {{- end }}
  POSTGRES_DATABASE: {{ default "vulcan_production" .Values.postgresql.auth.database | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.env.SECRET_KEY_BASE | b64enc | quote }}
  CIPHER_PASSWORD: {{ .Values.env.CIPHER_PASSWORD | b64enc | quote }}
  CIPHER_SALT: {{ .Values.env.CIPHER_SALT | b64enc | quote }}
  LDAP_PASSWORD: {{ .Values.env.VULCAN_LDAP_ADMIN_PASS | b64enc | quote }}
