apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulcan-helm.fullname" . }}
  labels: {{- include "vulcan-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vulcan.service.type }}
  ports:
    - port: {{ .Values.vulcan.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "vulcan-helm.selectorLabels" . | nindent 4 }}
