apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulcan.fullname" . }}
  labels:
    app: {{ include "vulcan.fullname" . }}
spec:
  type: {{ .Values.vulcan.service.type }}
  ports:
    - port: {{ .Values.vulcan.service.port }}
      targetPort: {{ .Values.vulcan.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "vulcan.selectorLabels" . | nindent 4 }}
