apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulcan.fullname" . }}
  labels:
    app: {{ template "vulcan.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- with .Values.services.annotations }}
    annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.services.type }}
  ports:
    - port: {{ int .Values.services.internalPort }}
      targetPort: {{ int .Values.services.targetPort }}
      name: {{ .Values.services.name | quote}}
  selector: {{- include "vulcan.selectorLabels" . | nindent 4 }}
status:
  loadBalancer: {}
