# Rails Config
RACK_ENV: "production"
RAILS_ENV: "production"
RAILS_LOG_TO_STDOUT: "enabled"
RAILS_SERVE_STATIC_FILES: "enabled"
# Postgres Config
POSTGRES_PORT: "5432"
POSTGRES_DB: "vulcan_psql_production"
POSTGRES_USER: "vulcanpostgres"
PGDATA: "/var/lib/postgresql/data"
# Vulcan App config: Configure these variables to your need
VULCAN_WELCOME_TEXT: "Thank you for visiting Vulcan. Please sign in to begin"
VULCAN_CONTACT_EMAIL: "do_not_reply@vulcan"
VULCAN_ENABLE_USER_REGISTRATION: "true"
VULCAN_PROJECT_CREATE_PERMISSION_ENABLED: "true"
VULCAN_ENABLE_SMTP: "false"
VULCAN_SMTP_ADDRESS: ""
VULCAN_SMTP_PORT: ""
VULCAN_SMTP_DOMAIN: ""
VULCAN_SMTP_AUTHENTICATION: ""
VULCAN_SMTP_TLS: ""
VULCAN_SMTP_OPENSSL_VERIFY_MODE: ""
VULCAN_SMTP_ENABLE_STARTTLS_AUTO: ""
VULCAN_SMTP_SERVER_USERNAME: ""
VULCAN_SMTP_SERVER_PASSWORD: ""
VULCAN_ENABLE_LOCAL_LOGIN: "true"
VULCAN_ENABLE_EMAIL_CONFIRMATION: "false"
VULCAN_SESSION_TIMEOUT: "60"
VULCAN_ENABLE_LDAP: "false"
VULCAN_LDAP_HOST: "localhost"
VULCAN_LDAP_PORT: "389"
VULCAN_LDAP_TITLE: "LDAP"
VULCAN_LDAP_ATTRIBUTE: "uid"
VULCAN_LDAP_ENCRYPTION: "plain"
VULCAN_LDAP_BIND_DN: ""
VULCAN_LDAP_ADMIN_PASS: ""
VULCAN_LDAP_BASE: ""
VULCAN_LDAP_CERT_VERIFY: "false"
